### ISSUE TITLE
readlink portability in kernel makefile

### ISSUE THREAD

**Issue by stormspirit** [jhshi/blog_source#3]
Hi Jinghao,
Since I didn't find a comment section in your post http://jhshi.me/2014/06/30/build-kernel-in-tree-with-aosp-for-nexus-5-hammerhead/, I'll comment here.

Thanks for writing it up. I was building the phonelab release on a nexus 5 in Mac. Everything works fine until towards building the kernel part. It encountered an error:

```
cp out/target/product/hammerhead/obj/KERNEL_OBJ/arch/arm/boot/zImage-dtb out/target/product/hammerhead/kernel
cp: out/target/product/hammerhead/obj/KERNEL_OBJ/arch/arm/boot/zImage-dtb: No such file or directory
make: *** [out/target/product/hammerhead/kernel] Error 1
```

The `KERNEL_OBJ` directory is empty but the image files gets generated at kernel/arch/arm/boot. Not the out directory.

This does not happen on a Linux machine. After digging around in your post, I find it's because of the use of `readlink` in `kernel/AndroidKernel.mk`, which is very rudimentary in Mac, e.g., it does not support `-e` or `-f` flag. So the `FULL_KERNEL_OUT` will be empty. A quick fix would be install the coreutils version of `readlink` in Mac and then alias the `readlink` to `greadlink`. Or the `readlink -f` can be replaced by more portable version with BASH scripting like http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac.

Just want to add a note if others encounter similar issues :)

**Comment by jhshi** [comment]
Thanks. This information may be useful to other Mac users. I'll try to point it out in the post.
